words := he the hen other the%
get-the:
	@echo he matches: $(filter he, $(words))
	@echo %he matches: $(filter %he, $(words))
	@echo he% matches: $(filter he%, $(words))
	@echo %he% matches: $(filter %he%, $(words))
