CC=cc

# Section 9.0.
run-program01: program01-basic-priority-queue-adt.c
	@cat $<

run-exercise01: exercise01.md
	@cat $<
run-exercise03-04: exercise03-04.md
	@cat $<

# Section 9.1. Elementary Implementation
run-program02: program02-array-implementation-of-a-priority-queue.c
	@cat $<

# Section 9.2. Heap Data Structure

# Section 9.3. Algorithms on Heaps
run-program03: program03-bottom-up-heapify.c
	@cat $<

run-program04: program04-top-down-heapify.c
	@cat $<

run-program05: program05-heap-based-priority-queue.c
	@cat $<

# Section 9.4. Heapsort
run-program06: program06-sorting-with-a-priority-queue.c
	@cat $<

run-program07: program07-heapsort.c
	@cat $<

# Section 9.5. Priority-Queue ADT
run-program08: program08-first-class-priority-queue-adt.c
	@cat $<

run-program09: program09-unordered-doubly-linked-list-priority-queue.c
	@cat $<

run-program10: program10-doubly-linked-list-priority-queue-continued.c
	@cat $<

# Section 9.6. Priority Queues for Index Items
run-program11: program11-priority-queue-adt-interface-for-index-items
	@cat $<

run-program12: program12-index-heap-based-priority-queue
	@cat $<
