##
## Makefile<2> for  in /home/nico/lang/c/strace
## 
## Made by nicolas
## Login   <nico@epita.fr>
## 
## Started on  Mon Jan  2 09:55:45 2006 nicolas
## Last update Mon Jan  2 09:57:05 2006 nicolas
##

all:
	sh ./mkioctls /usr/include > ./ioctl.c