
typedef struct 
{
  char*	name;
  int	arg_nbr;
  char*	args_type[25];
  char* ret_type;
}		syscnfo_t;

typedef int strace_openmode;
typedef int strace_accessmode;
typedef int strace_ioctl;
typedef int strace_fcntl;
typedef int strace_filedesc;
typedef int strace_signal;
typedef int strace_mmapprot;
typedef int strace_mmapflags;

syscnfo_t	syscalls_info[] = { 
	{ "syscall", 1, { "int", NULL }, "int"},
	{ "exit", 1, {  "int", NULL }, "void"},
	{ "fork", 1, { "void", NULL }, "int"},
	{ "read", 3, {  "strace_filedesc", "void *", "size_t", NULL }, "ssize_t"},
	{ "write", 3, {  "strace_filedesc", "const void *", "size_t", NULL }, "ssize_t"},
	{ "open", 3, { "char *", "strace_openmode", "int", NULL }, "int"},
	{ "close", 1, { "int", NULL }, "int"},
	{ "wait4", 1, { "int", NULL }, "int"},
	{ "creat", 2, { "char *", "int", NULL }, "int"},
	{ "link", 2, { "char *", "char *", NULL }, "int"},
	{ "unlink", 1, { "char *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "chdir", 1, { "char *", NULL }, "int"},
	{ "fchdir", 1, { "int", NULL }, "int"},
	{ "mknod", 3, { "char *", "int", "int", NULL }, "int"},
	{ "chmod", 2, { "char *", "int", NULL }, "int"},
	{ "chown", 3, { "char *", "int", "int", NULL }, "int"},
	{ "break", 1, { "int", NULL }, "int"},
	{ "getfsstat", 3, { "struct ostatfs *", "long", "int", NULL }, "int"},
	{ "lseek", 3, {  "strace_filedesc", "long", "int", NULL }, "long"},
	{ "getpid", 1, { "void", NULL }, "pid_t"},
	{ "mount", 4, { "char *", "char *", "int", "caddr_t", NULL }, "int"},
	{ "unmount", 2, { "char *", "int", NULL }, "int"},
	{ "setuid", 1, { "uid_t", NULL }, "int"},
	{ "getuid", 1, { "void", NULL }, "uid_t"},
	{ "geteuid", 1, { "void", NULL }, "uid_t"},
	{ "ptrace", 4, { "int", "pid_t", "caddr_t", "int", NULL }, "int"},
	{ "recvmsg", 3, { "int", "struct msghdr *", "int", NULL }, "int"},
	{ "sendmsg", 3, { "int", "struct msghdr *", "int", NULL }, "int"},
	{ "recvfrom", 6, { "int", "caddr_t", "size_t", "int", "struct sockaddr * __restrict", "__socklen_t * __restrict", NULL }, "int"},
	{ "accept", 3, { "int", "struct sockaddr * __restrict", "__socklen_t * __restrict", NULL }, "int"},
	{ "getpeername", 3, { "int", "struct sockaddr * __restrict", "__socklen_t * __restrict", NULL }, "int"},
	{ "getsockname", 3, { "int", "struct sockaddr * __restrict", "__socklen_t * __restrict", NULL }, "int"},
	{ "access", 2, { "char *", "strace_accessmode", NULL }, "int"},
	{ "chflags", 2, { "char *", "int", NULL }, "int"},
	{ "fchflags", 2, { "int", "int", NULL }, "int"},
	{ "sync", 1, { "void", NULL }, "int"},
	{ "kill", 2, { "int", "strace_signal", NULL }, "int"},
	{ "stat", 2, { "char *", "struct ostat *", NULL }, "int"},
	{ "getppid", 1, { "void", NULL }, "pid_t"},
	{ "lstat", 2, { "char *", "struct ostat *", NULL }, "int"},
	{ "dup", 1, { "u_int", NULL }, "int"},
	{ "pipe", 1, { "void", NULL }, "int"},
	{ "getegid", 1, { "void", NULL }, "gid_t"},
	{ "profil", 4, { "caddr_t", "size_t", "size_t", "u_int", NULL }, "int"},
	{ "ktrace", 4, { "const char *", "int", "int", "int", NULL }, "int"},
	{ "sigaction", 3, {  "strace_signal", "struct osigaction *", "struct osigaction *", NULL }, "int"},
	{ "getgid", 1, { "void", NULL }, "gid_t"},
	{ "sigprocmask", 2, { "int", "osigset_t", NULL }, "int"},
	{ "getlogin", 2, { "char *", "u_int", NULL }, "int"},
	{ "setlogin", 1, { "char *", NULL }, "int"},
	{ "acct", 1, { "char *", NULL }, "int"},
	{ "sigpending", 1, { "void", NULL }, "int"},
	{ "sigaltstack", 2, { "stack_t *", "stack_t *", NULL }, "int"},
	{ "ioctl", 3, {  "strace_filedesc", "strace_ioctl", "caddr_t", NULL }, "int"},
	{ "reboot", 1, { "int", NULL }, "int"},
	{ "revoke", 1, { "char *", NULL }, "int"},
	{ "symlink", 2, { "char *", "char *", NULL }, "int"},
	{ "readlink", 3, { "char *", "char *", "int", NULL }, "int"},
	{ "execve", 3, { "char *", "char **", "char **", NULL }, "int"},
	{ "umask", 1, { "int", NULL }, "int"},
	{ "chroot", 1, { "char *", NULL }, "int"},
	{ "fstat", 2, { "int", "struct ostat *", NULL }, "int"},
	{ "getkerninfo", 1, { "int", NULL }, "int"},
	{ "getpagesize", 1, { "int", NULL }, "int"},
	{ "msync", 3, { "void *", "size_t", "int", NULL }, "int"},
	{ "vfork", 1, { "void", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "sbrk", 1, { "int", NULL }, "int"},
	{ "sstk", 1, { "int", NULL }, "int"},
	{ "mmap", 6, { "void *", "int", "strace_mmapprot", "strace_mmapflags", "strace_filedesc", "long", NULL }, "int"},
	{ "vadvise", 1, { "int", NULL }, "int"},
	{ "munmap", 2, { "void *", "size_t", NULL }, "int"},
	{ "mprotect", 3, { "const void *", "size_t", "int", NULL }, "int"},
	{ "madvise", 3, { "void *", "size_t", "int", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "mincore", 3, { "const void *", "size_t", "char *", NULL }, "int"},
	{ "getgroups", 2, { "u_int", "gid_t *", NULL }, "int"},
	{ "setgroups", 2, { "u_int", "gid_t *", NULL }, "int"},
	{ "getpgrp", 1, { "void", NULL }, "int"},
	{ "setpgid", 2, { "int", "int", NULL }, "int"},
	{ "setitimer", 3, { "u_int", "struct itimerval *", "struct itimerval *", NULL }, "int"},
	{ "wait", 1, { "void", NULL }, "int"},
	{ "swapon", 1, { "char *", NULL }, "int"},
	{ "getitimer", 2, { "u_int", "struct itimerval *", NULL }, "int"},
	{ "gethostname", 1, { "int", NULL }, "int"},
	{ "sethostname", 1, { "int", NULL }, "int"},
	{ "getdtablesize", 1, { "void", NULL }, "int"},
	{ "dup2", 2, { "u_int", "u_int", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "fcntl", 3, {  "strace_filedesc", "strace_fcntl", "long", NULL }, "int"},
	{ "select", 5, { "int", "fd_set *", "fd_set *", "fd_set *", "struct timeval *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "fsync", 1, { "int", NULL }, "int"},
	{ "setpriority", 3, { "int", "int", "int", NULL }, "int"},
	{ "socket", 3, { "int", "int", "int", NULL }, "int"},
	{ "connect", 3, { "int", "caddr_t", "int", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "getpriority", 2, { "int", "int", NULL }, "int"},
	{ "send", 4, { "int", "caddr_t", "int", "int", NULL }, "int"},
	{ "recv", 4, { "int", "caddr_t", "int", "int", NULL }, "int"},
	{ "sigreturn", 1, { " struct osigcontext *", NULL }, "int"},
	{ "bind", 3, { "int", "caddr_t", "int", NULL }, "int"},
	{ "setsockopt", 5, { "int", "int", "int", "caddr_t", "int", NULL }, "int"},
	{ "listen", 2, { "int", "int", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "sigvec", 3, { "int", "struct sigvec *", "struct sigvec *", NULL }, "int"},
	{ "sigblock", 1, { "int", NULL }, "int"},
	{ "sigsetmask", 1, { "int", NULL }, "int"},
	{ "sigsuspend", 1, { "osigset_t", NULL }, "int"},
	{ "sigstack", 2, { "struct sigstack *", "struct sigstack *", NULL }, "int"},
	{ "recvmsg", 3, { "int", "struct omsghdr *", "int", NULL }, "int"},
	{ "sendmsg", 3, { "int", "caddr_t", "int", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "gettimeofday", 2, { "struct timeval *", "struct timezone *", NULL }, "int"},
	{ "getrusage", 2, { "int", "struct rusage *", NULL }, "int"},
	{ "getsockopt", 5, { "int", "int", "int", "caddr_t", "int *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "readv", 3, { "int", "struct iovec *", "u_int", NULL }, "int"},
	{ "writev", 3, { "int", "struct iovec *", "u_int", NULL }, "int"},
	{ "settimeofday", 2, { "struct timeval *", "struct timezone *", NULL }, "int"},
	{ "fchown", 3, { "int", "int", "int", NULL }, "int"},
	{ "fchmod", 2, { "int", "int", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "setreuid", 2, { "int", "int", NULL }, "int"},
	{ "setregid", 2, { "int", "int", NULL }, "int"},
	{ "rename", 2, { "char *", "char *", NULL }, "int"},
	{ "truncate", 2, { "char *", "long", NULL }, "int"},
	{ "ftruncate", 2, { "int", "long", NULL }, "int"},
	{ "flock", 2, { "int", "int", NULL }, "int"},
	{ "mkfifo", 2, { "char *", "int", NULL }, "int"},
	{ "sendto", 6, { "int", "caddr_t", "size_t", "int", "caddr_t", "int", NULL }, "int"},
	{ "shutdown", 2, { "int", "int", NULL }, "int"},
	{ "socketpair", 4, { "int", "int", "int", "int *", NULL }, "int"},
	{ "mkdir", 2, { "char *", "int", NULL }, "int"},
	{ "rmdir", 1, { "char *", NULL }, "int"},
	{ "utimes", 2, { "char *", "struct timeval *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "adjtime", 2, { "struct timeval *", "struct timeval *", NULL }, "int"},
	{ "getpeername", 3, { "int", "caddr_t", "int *", NULL }, "int"},
	{ "gethostid", 1, { "void", NULL }, "long"},
	{ "sethostid", 1, { "long", NULL }, "int"},
	{ "getrlimit", 2, { "u_int", "struct orlimit *", NULL }, "int"},
	{ "setrlimit", 2, { "u_int", "struct orlimit *", NULL }, "int"},
	{ "killpg", 2, { "int", "int", NULL }, "int"},
	{ "setsid", 1, { "void", NULL }, "int"},
	{ "quotactl", 4, { "char *", "int", "int", "caddr_t", NULL }, "int"},
	{ "quota", 1, { "void", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "statfs", 2, { "char *", "struct ostatfs *", NULL }, "int"},
	{ "fstatfs", 2, { "int", "struct ostatfs *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "lgetfh", 2, { "char *", "struct fhandle *", NULL }, "int"},
	{ "getfh", 2, { "char *", "struct fhandle *", NULL }, "int"},
	{ "getdomainname", 2, { "char *", "int", NULL }, "int"},
	{ "setdomainname", 2, { "char *", "int", NULL }, "int"},
	{ "uname", 1, { "struct utsname *", NULL }, "int"},
	{ "sysarch", 2, { "int", "char *", NULL }, "int"},
	{ "rtprio", 3, { "int", "pid_t", "struct rtprio *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "semsys", 5, { "int", "int", "int", "int", "int", NULL }, "int"},
	{ "msgsys", 6, { "int", "int", "int", "int", "int", "int", NULL }, "int"},
	{ "shmsys", 4, { "int", "int", "int", "int", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "pread", 5, { "int", "void *", "size_t", "int", "off_t", NULL }, "ssize_t"},
	{ "pwrite", 5, { "int", "const void *", "size_t", "int", "off_t", NULL }, "ssize_t"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "ntp_adjtime", 1, { "struct timex *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "setgid", 1, { "gid_t", NULL }, "int"},
	{ "setegid", 1, { "gid_t", NULL }, "int"},
	{ "seteuid", 1, { "uid_t", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "stat", 2, { "char *", "struct stat *", NULL }, "int"},
	{ "fstat", 2, { "int", "struct stat *", NULL }, "int"},
	{ "lstat", 2, { "char *", "struct stat *", NULL }, "int"},
	{ "pathconf", 2, { "char *", "int", NULL }, "int"},
	{ "fpathconf", 2, { "int", "int", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "getrlimit", 1, { "int", NULL }, "int"},
	{ "setrlimit", 1, { "int", NULL }, "int"},
	{ "getdirentries", 4, { "int", "char *", "u_int", "long *", NULL }, "int"},
	{ "mmap", 7, { "caddr_t", "size_t", "strace_mmapprot", "strace_mmapflags", "strace_filedesc", "int", "off_t", NULL }, "caddr_t"},
	{ "__syscall", 1, { "int", NULL }, "int"},
	{ "lseek", 4, {  "strace_filedesc", "int", "off_t", "int", NULL }, "off_t"},
	{ "truncate", 3, { "char *", "int", "off_t", NULL }, "int"},
	{ "ftruncate", 3, { "int", "int", "off_t", NULL }, "int"},
	{ "__sysctl", 1, { "int", NULL }, "int"},
	{ "mlock", 2, { "const void *", "size_t", NULL }, "int"},
	{ "munlock", 2, { "const void *", "size_t", NULL }, "int"},
	{ "undelete", 1, { "char *", NULL }, "int"},
	{ "futimes", 2, { "int", "struct timeval *", NULL }, "int"},
	{ "getpgid", 1, { "pid_t", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "poll", 3, { "struct pollfd *", "u_int", "int", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "__semctl", 4, { "int", "int", "int", "union semun *", NULL }, "int"},
	{ "semget", 3, { "key_t", "int", "int", NULL }, "int"},
	{ "semop", 3, { "int", "struct sembuf *", "size_t", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "msgctl", 3, { "int", "int", "struct msqid_ds *", NULL }, "int"},
	{ "msgget", 2, { "key_t", "int", NULL }, "int"},
	{ "msgsnd", 4, { "int", "const void *", "size_t", "int", NULL }, "int"},
	{ "msgrcv", 5, { "int", "void *", "size_t", "long", "int", NULL }, "int"},
	{ "shmat", 3, { "int", "const void *", "int", NULL }, "int"},
	{ "shmctl", 3, { "int", "int", "struct shmid_ds *", NULL }, "int"},
	{ "shmdt", 1, { "const void *", NULL }, "int"},
	{ "shmget", 3, { "key_t", "size_t", "int", NULL }, "int"},
	{ "clock_gettime", 2, { "clockid_t", "struct timespec *", NULL }, "int"},
	{ "clock_settime", 2, { "clockid_t", "const struct timespec *", NULL }, "int"},
	{ "clock_getres", 2, { "clockid_t", "struct timespec *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "nanosleep", 2, { "const struct timespec *", "struct timespec *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "ntp_gettime", 1, { "struct ntptimeval *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "minherit", 3, { "void *", "size_t", "int", NULL }, "int"},
	{ "rfork", 1, { "int", NULL }, "int"},
	{ "openbsd_poll", 3, { "struct pollfd *", "u_int", "int", NULL }, "int"},
	{ "issetugid", 1, { "void", NULL }, "int"},
	{ "lchown", 3, { "char *", "int", "int", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "getdents", 3, { "int", "char *", "size_t", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "lchmod", 2, { "char *", "mode_t", NULL }, "int"},
	{ "netbsd_lchown", 1, { "int", NULL }, "int"},
	{ "lutimes", 2, { "char *", "struct timeval *", NULL }, "int"},
	{ "netbsd_msync", 1, { "int", NULL }, "int"},
	{ "nstat", 2, { "char *", "struct nstat *", NULL }, "int"},
	{ "nfstat", 2, { "int", "struct nstat *", NULL }, "int"},
	{ "nlstat", 2, { "char *", "struct nstat *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "preadv", 4, { "int", "struct iovec *", "u_int", "off_t", NULL }, "ssize_t"},
	{ "pwritev", 4, { "int", "struct iovec *", "u_int", "off_t", NULL }, "ssize_t"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "fhstatfs", 2, { " const struct fhandle *", "struct ostatfs *", NULL }, "int"},
	{ "fhopen", 2, { "const struct fhandle *", "int", NULL }, "int"},
	{ "fhstat", 2, { "const struct fhandle *", "struct stat *", NULL }, "int"},
	{ "modnext", 1, { "int", NULL }, "int"},
	{ "modstat", 2, { "int", "struct module_stat *", NULL }, "int"},
	{ "modfnext", 1, { "int", NULL }, "int"},
	{ "modfind", 1, { "const char *", NULL }, "int"},
	{ "kldload", 1, { "const char *", NULL }, "int"},
	{ "kldunload", 1, { "int", NULL }, "int"},
	{ "kldfind", 1, { "const char *", NULL }, "int"},
	{ "kldnext", 1, { "int", NULL }, "int"},
	{ "kldstat", 2, { "int", "struct kld_file_stat*", NULL }, "int"},
	{ "kldfirstmod", 1, { "int", NULL }, "int"},
	{ "getsid", 1, { "pid_t", NULL }, "int"},
	{ "setresuid", 3, { "uid_t", "uid_t", "uid_t", NULL }, "int"},
	{ "setresgid", 3, { "gid_t", "gid_t", "gid_t", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "aio_return", 1, { "struct aiocb *", NULL }, "int"},
	{ "aio_suspend", 3, { " struct aiocb * const *", "int", "const struct timespec *", NULL }, "int"},
	{ "aio_cancel", 2, { "int", "struct aiocb *", NULL }, "int"},
	{ "aio_error", 1, { "struct aiocb *", NULL }, "int"},
	{ "aio_read", 1, { "struct aiocb *", NULL }, "int"},
	{ "aio_write", 1, { "struct aiocb *", NULL }, "int"},
	{ "lio_listio", 4, { "int", "struct aiocb * const *", "int", "struct sigevent *", NULL }, "int"},
	{ "yield", 1, { "void", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "mlockall", 1, { "int", NULL }, "int"},
	{ "munlockall", 1, { "void", NULL }, "int"},
	{ "__getcwd", 2, { "u_char *", "u_int", NULL }, "int"},
	{ "", 2, { "pid_t", "const struct sched_param *", NULL }, "int sched_setparam"},
	{ "", 2, { "pid_t", "struct sched_param *", NULL }, "int sched_getparam"},
	{ "", 3, { "pid_t", "int", "const struct sched_param *", NULL }, "int sched_setscheduler"},
	{ "", 1, { "pid_t", NULL }, "int sched_getscheduler"},
	{ "", 1, { "void", NULL }, "int sched_yield"},
	{ "", 1, { "int", NULL }, "int sched_get_priority_max"},
	{ "", 1, { "int", NULL }, "int sched_get_priority_min"},
	{ "", 2, { "pid_t", "struct timespec *", NULL }, "int sched_rr_get_interval"},
	{ "utrace", 2, { "const void *", "size_t", NULL }, "int"},
	{ "sendfile", 7, { "int", "int", "off_t", "size_t", "struct sf_hdtr *", "off_t *", "int", NULL }, "int"},
	{ "kldsym", 3, { "int", "int", "void *", NULL }, "int"},
	{ "jail", 1, { "struct jail *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "sigprocmask", 3, { "int", "const sigset_t *", "sigset_t *", NULL }, "int"},
	{ "sigsuspend", 1, { "const sigset_t *", NULL }, "int"},
	{ "sigaction", 3, {  "strace_signal", "const struct sigaction *", "struct sigaction *", NULL }, "int"},
	{ "sigpending", 1, { "sigset_t *", NULL }, "int"},
	{ "sigreturn", 1, { " const struct ucontext4 *", NULL }, "int"},
	{ "sigtimedwait", 3, { "const sigset_t *", "siginfo_t *", "const struct timespec *", NULL }, "int"},
	{ "sigwaitinfo", 2, { "const sigset_t *", "siginfo_t *", NULL }, "int"},
	{ "__acl_get_file", 3, { "const char *", "acl_type_t", "struct acl *", NULL }, "int"},
	{ "__acl_set_file", 3, { "const char *", "acl_type_t", "struct acl *", NULL }, "int"},
	{ "__acl_get_fd", 3, { "int", "acl_type_t", "struct acl *", NULL }, "int"},
	{ "__acl_set_fd", 3, { "int", "acl_type_t", "struct acl *", NULL }, "int"},
	{ "__acl_delete_file", 2, { "const char *", "acl_type_t", NULL }, "int"},
	{ "__acl_delete_fd", 2, { "int", "acl_type_t", NULL }, "int"},
	{ "__acl_aclcheck_file", 3, { "const char *", "acl_type_t", "struct acl *", NULL }, "int"},
	{ "__acl_aclcheck_fd", 3, { "int", "acl_type_t", "struct acl *", NULL }, "int"},
	{ "extattrctl", 5, { "const char *", "int", "const char *", "int", "const char *", NULL }, "int"},
	{ "extattr_set_file", 5, { "const char *", "int", "const char *", "void *", "size_t", NULL }, "int"},
	{ "extattr_get_file", 5, { "const char *", "int", "const char *", "void *", "size_t", NULL }, "ssize_t"},
	{ "extattr_delete_file", 3, { "const char *", "int", "const char *", NULL }, "int"},
	{ "aio_waitcomplete", 2, { " struct aiocb **", "struct timespec *", NULL }, "int"},
	{ "getresuid", 3, { "uid_t *", "uid_t *", "uid_t *", NULL }, "int"},
	{ "getresgid", 3, { "gid_t *", "gid_t *", "gid_t *", NULL }, "int"},
	{ "kqueue", 1, { "void", NULL }, "int"},
	{ "kevent", 6, { "int", "struct kevent *", "int", "struct kevent *", "int", "const struct timespec *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "extattr_set_fd", 5, { "int", "int", "const char *", "void *", "size_t", NULL }, "int"},
	{ "extattr_get_fd", 5, { "int", "int", "const char *", "void *", "size_t", NULL }, "ssize_t"},
	{ "extattr_delete_fd", 3, { "int", "int", "const char *", NULL }, "int"},
	{ "__setugid", 1, { "int", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "eaccess", 2, { "char *", "int", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "nmount", 3, { "struct iovec *", "unsigned int", "int", NULL }, "int"},
	{ "kse_exit", 1, { "void", NULL }, "int"},
	{ "kse_wakeup", 1, { "struct kse_mailbox *", NULL }, "int"},
	{ "kse_create", 2, { "struct kse_mailbox *", "int", NULL }, "int"},
	{ "kse_thr_interrupt", 3, { " struct kse_thr_mailbox *", "int", "long", NULL }, "int"},
	{ "kse_release", 1, { "struct timespec *", NULL }, "int"},
	{ "__mac_get_proc", 1, { "struct mac *", NULL }, "int"},
	{ "__mac_set_proc", 1, { "struct mac *", NULL }, "int"},
	{ "__mac_get_fd", 2, { "int", "struct mac *", NULL }, "int"},
	{ "__mac_get_file", 2, { "const char *", "struct mac *", NULL }, "int"},
	{ "__mac_set_fd", 2, { "int", "struct mac *", NULL }, "int"},
	{ "__mac_set_file", 2, { "const char *", "struct mac *", NULL }, "int"},
	{ "kenv", 4, { "int", "const char *", "char *", "int", NULL }, "int"},
	{ "lchflags", 2, { "const char *", "int", NULL }, "int"},
	{ "uuidgen", 2, { "struct uuid *", "int", NULL }, "int"},
	{ "sendfile", 7, { "int", "int", "off_t", "size_t", "struct sf_hdtr *", "off_t *", "int", NULL }, "int"},
	{ "mac_syscall", 3, { "const char *", "int", "void *", NULL }, "int"},
	{ "getfsstat", 3, { "struct statfs *", "long", "int", NULL }, "int"},
	{ "statfs", 2, { "char *", "struct statfs *", NULL }, "int"},
	{ "fstatfs", 2, { "int", "struct statfs *", NULL }, "int"},
	{ "fhstatfs", 2, { "const struct fhandle *", "struct statfs *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "ksem_close", 1, { "semid_t", NULL }, "int"},
	{ "ksem_post", 1, { "semid_t", NULL }, "int"},
	{ "ksem_wait", 1, { "semid_t", NULL }, "int"},
	{ "ksem_trywait", 1, { "semid_t", NULL }, "int"},
	{ "ksem_init", 2, { "semid_t *", "unsigned int", NULL }, "int"},
	{ "ksem_open", 5, { "semid_t *", "const char *", "int", "mode_t", "unsigned int", NULL }, "int"},
	{ "ksem_unlink", 1, { "const char *", NULL }, "int"},
	{ "ksem_getvalue", 2, { "semid_t", "int *", NULL }, "int"},
	{ "ksem_destroy", 1, { "semid_t", NULL }, "int"},
	{ "__mac_get_pid", 2, { "pid_t", "struct mac *", NULL }, "int"},
	{ "__mac_get_link", 2, { "const char *", "struct mac *", NULL }, "int"},
	{ "__mac_set_link", 2, { "const char *", "struct mac *", NULL }, "int"},
	{ "extattr_set_link", 5, { "const char *", "int", "const char *", "void *", "size_t", NULL }, "int"},
	{ "extattr_get_link", 5, { "const char *", "int", "const char *", "void *", "size_t", NULL }, "ssize_t"},
	{ "extattr_delete_link", 3, { "const char *", "int", "const char *", NULL }, "int"},
	{ "__mac_execve", 4, { "char *", "char **", "char **", "struct mac *", NULL }, "int"},
	{ "sigaction", 3, {  "strace_signal", "const struct sigaction *", "struct sigaction *", NULL }, "int"},
	{ "sigreturn", 1, { " const struct __ucontext *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "getcontext", 1, { "struct __ucontext *", NULL }, "int"},
	{ "setcontext", 1, { " const struct __ucontext *", NULL }, "int"},
	{ "swapcontext", 2, { "struct __ucontext *", "const struct __ucontext *", NULL }, "int"},
	{ "swapoff", 1, { "const char *", NULL }, "int"},
	{ "__acl_get_link", 3, { "const char *", "acl_type_t", "struct acl *", NULL }, "int"},
	{ "__acl_set_link", 3, { "const char *", "acl_type_t", "struct acl *", NULL }, "int"},
	{ "__acl_delete_link", 2, { "const char *", "acl_type_t", NULL }, "int"},
	{ "__acl_aclcheck_link", 3, { "const char *", "acl_type_t", "struct acl *", NULL }, "int"},
	{ "sigwait", 2, { "const sigset_t *", "int *", NULL }, "int"},
	{ "thr_create", 3, { "ucontext_t *", "long *", "int", NULL }, "int"},
	{ "thr_exit", 1, { "long *", NULL }, "void"},
	{ "thr_self", 1, { "long *", NULL }, "int"},
	{ "thr_kill", 2, { "long", "int", NULL }, "int"},
	{ "_umtx_lock", 1, { "struct umtx *", NULL }, "int"},
	{ "_umtx_unlock", 1, { "struct umtx *", NULL }, "int"},
	{ "jail_attach", 1, { "int", NULL }, "int"},
	{ "extattr_list_fd", 4, { "int", "int", "void *", "size_t", NULL }, "ssize_t"},
	{ "extattr_list_file", 4, { " const char *", "int", "void *", "size_t", NULL }, "ssize_t"},
	{ "extattr_list_link", 4, { " const char *", "int", "void *", "size_t", NULL }, "ssize_t"},
	{ "kse_switchin", 2, { " struct kse_thr_mailbox *", "int", NULL }, "int"},
	{ "ksem_timedwait", 2, { "semid_t", "struct timespec *", NULL }, "int"},
	{ "thr_suspend", 1, { " const struct timespec *", NULL }, "int"},
	{ "thr_wake", 1, { "long", NULL }, "int"},
	{ "kldunloadf", 2, { "int", "int", NULL }, "int"},
	{ "audit", 2, { "const void *", "u_int", NULL }, "int"},
	{ "auditon", 3, { "int", "void *", "u_int", NULL }, "int"},
	{ "getauid", 1, { "uid_t *", NULL }, "int"},
	{ "setauid", 1, { "uid_t *", NULL }, "int"},
	{ "getaudit", 1, { "struct auditinfo *", NULL }, "int"},
	{ "setaudit", 1, { "struct auditinfo *", NULL }, "int"},
	{ "getaudit_addr", 2, { " struct auditinfo_addr *", "u_int", NULL }, "int"},
	{ "setaudit_addr", 2, { " struct auditinfo_addr *", "u_int", NULL }, "int"},
	{ "auditctl", 2, { "int", "char *", NULL }, "int"},
	{ "_umtx_op", 5, { "struct umtx *", "int", "long", "void *", "void *", NULL }, "int"},
	{ "thr_new", 2, { "struct thr_param *", "int", NULL }, "int"},

};


#include <sys/param.h>
#include <sys/sysent.h>

#include <ucontext.h>
#include <sys/time.h>

typedef int acl_type_t;
typedef int semid_t;
typedef unsigned int osigset_t;

typedef struct
{
  char*	str;
  int	size;
} param_size_t;

param_size_t	params_size[] =
  {
	{"struct __ucontext *", sizeof(struct __ucontext *)},
	{"sigset_t *", sizeof(sigset_t *)},
	{"key_t", sizeof(key_t)},
	{"struct timeval *", sizeof(struct timeval *)},
	{"caddr_t", sizeof(caddr_t)},
	{"clockid_t", sizeof(clockid_t)},
	{"const struct __ucontext *", sizeof(const struct __ucontext *)},
	{"struct sembuf *", sizeof(struct sembuf *)},
	{"struct sigevent *", sizeof(struct sigevent *)},
	{"struct shmid_ds *", sizeof(struct shmid_ds *)},
	{"strace_ioctl", sizeof(strace_ioctl)},
	{"int *", sizeof(int *)},
	{"struct omsghdr *", sizeof(struct omsghdr *)},
	{"int", sizeof(int)},
	{"gid_t *", sizeof(gid_t *)},
	{"struct utsname *", sizeof(struct utsname *)},
	{"const struct timespec *", sizeof(const struct timespec *)},
	{"struct auditinfo *", sizeof(struct auditinfo *)},
	{"fd_set *", sizeof(fd_set *)},
	{"long *", sizeof(long *)},
	{"uid_t", sizeof(uid_t)},
	{"struct msqid_ds *", sizeof(struct msqid_ds *)},
	{"uid_t", sizeof(uid_t)},
	{"strace_openmode", sizeof(strace_openmode)},
	{"acl_type_t", sizeof(acl_type_t)},
	{"size_t", sizeof(size_t)},
	{"struct kse_thr_mailbox *", sizeof(struct kse_thr_mailbox *)},
	{"struct kevent *", sizeof(struct kevent *)},
	{"struct timespec *", sizeof(struct timespec *)},
	{"semid_t *", sizeof(semid_t *)},
	{"semid_t", sizeof(semid_t)},
	{"struct auditinfo_addr *", sizeof(struct auditinfo_addr *)},
	{"long", sizeof(long)},
	{"strace_mmapflags", sizeof(strace_mmapflags)},
	{"char *", sizeof(char *)},
	{"strace_accessmode", sizeof(strace_accessmode)},
	{"const struct fhandle *", sizeof(const struct fhandle *)},
	{"off_t *", sizeof(off_t *)},
	{"strace_filedesc", sizeof(strace_filedesc)},
	{"gid_t *", sizeof(gid_t *)},
	{"struct fhandle *", sizeof(struct fhandle *)},
	{"pid_t", sizeof(pid_t)},
	{"const struct __ucontext *", sizeof(const struct __ucontext *)},
	{"struct osigcontext *", sizeof(struct osigcontext *)},
	{"const struct sigaction *", sizeof(const struct sigaction *)},
	{"struct ostatfs *", sizeof(struct ostatfs *)},
	{"struct ostat *", sizeof(struct ostat *)},
	{"osigset_t", sizeof(osigset_t)},
	{"const sigset_t *", sizeof(const sigset_t *)},
	{"struct jail *", sizeof(struct jail *)},
	{"caddr_t", sizeof(caddr_t)},
	{"const sigset_t *", sizeof(const sigset_t *)},
	{"struct itimerval *", sizeof(struct itimerval *)},
	{"long", sizeof(long)},
	{"stack_t *", sizeof(stack_t *)},
	{"off_t", sizeof(off_t)},
	{"siginfo_t *", sizeof(siginfo_t *)},
	{"unsigned int", sizeof(unsigned int)},
	{"const void *", sizeof(const void *)},
	{"struct acl *", sizeof(struct acl *)},
	{"struct sf_hdtr *", sizeof(struct sf_hdtr *)},
	{"u_int", sizeof(u_int)},
	{"strace_fcntl", sizeof(strace_fcntl)},
	{"struct sigaction *", sizeof(struct sigaction *)},
	{"struct timespec *", sizeof(struct timespec *)},
	{"strace_mmapprot", sizeof(strace_mmapprot)},
	{"void *", sizeof(void *)},
	{"ucontext_t *", sizeof(ucontext_t *)},
	{"stack_t *", sizeof(stack_t *)},
	{"struct aiocb **", sizeof(struct aiocb **)},
	{"struct mac *", sizeof(struct mac *)},
	{"osigset_t", sizeof(osigset_t)},
	{"union semun *", sizeof(union semun *)},
	{"const struct timespec *", sizeof(const struct timespec *)},
	{"int", sizeof(int)},
	{"struct module_stat *", sizeof(struct module_stat *)},
	{"const struct sched_param *", sizeof(const struct sched_param *)},
	{"struct ntptimeval *", sizeof(struct ntptimeval *)},
	{"void *", sizeof(void *)},
	{"void", sizeof(void)},
	{"long *", sizeof(long *)},
	{"struct rtprio *", sizeof(struct rtprio *)},
	{"struct pollfd *", sizeof(struct pollfd *)},
	{"struct aiocb *", sizeof(struct aiocb *)},
	{"const char *", sizeof(const char *)},
	{"struct timeval *", sizeof(struct timeval *)},
	{"char *", sizeof(char *)},
	{"sigset_t *", sizeof(sigset_t *)},
	{"struct sched_param *", sizeof(struct sched_param *)},
	{"struct ostatfs *", sizeof(struct ostatfs *)},
	{"const struct fhandle *", sizeof(const struct fhandle *)},
	{"strace_signal", sizeof(strace_signal)},
	{"struct timezone *", sizeof(struct timezone *)},
	{"uid_t *", sizeof(uid_t *)},
	{"struct umtx *", sizeof(struct umtx *)},
	{"__socklen_t * __restrict", sizeof(__socklen_t * __restrict)},
	{"struct thr_param *", sizeof(struct thr_param *)},
	{"struct nstat *", sizeof(struct nstat *)},
	{"const char *", sizeof(const char *)},
	{"struct statfs *", sizeof(struct statfs *)},
	{"struct sigvec *", sizeof(struct sigvec *)},
	{"struct osigaction *", sizeof(struct osigaction *)},
	{"struct orlimit *", sizeof(struct orlimit *)},
	{"const char *", sizeof(const char *)},
	{"u_int", sizeof(u_int)},
	{"uid_t *", sizeof(uid_t *)},
	{"struct mac *", sizeof(struct mac *)},
	{"pid_t", sizeof(pid_t)},
	{"struct timex *", sizeof(struct timex *)},
	{"gid_t", sizeof(gid_t)},
	{"struct aiocb * const *", sizeof(struct aiocb * const *)},
	{"u_char *", sizeof(u_char *)},
	{"struct rusage *", sizeof(struct rusage *)},
	{"struct aiocb *", sizeof(struct aiocb *)},
	{"struct iovec *", sizeof(struct iovec *)},
	{"mode_t", sizeof(mode_t)},
	{"struct sigstack *", sizeof(struct sigstack *)},
	{"const struct timespec *", sizeof(const struct timespec *)},
	{"struct uuid *", sizeof(struct uuid *)},
	{"struct msghdr *", sizeof(struct msghdr *)},
	{"char **", sizeof(char **)},
	{"struct kld_file_stat*", sizeof(struct kld_file_stat*)},
	{"struct aiocb * const *", sizeof(struct aiocb * const *)},
	{"const struct ucontext4 *", sizeof(const struct ucontext4 *)},
	{"struct kse_mailbox *", sizeof(struct kse_mailbox *)},
	{"struct sockaddr * __restrict", sizeof(struct sockaddr * __restrict)},
	{"gid_t", sizeof(gid_t)},
	{"struct statfs *", sizeof(struct statfs *)},
	{"struct stat *", sizeof(struct stat *)},
	{"struct sigstack *", sizeof(struct sigstack *)},
	{"struct iovec *", sizeof(struct iovec *)},
	{"const void *", sizeof(const void *)},

};
