
typedef struct 
{
  char*	name;
  int	arg_nbr;
  char*	args_type[25];
  char* ret_type;
}		syscnfo_t;

typedef int strace_openmode;
typedef int strace_accessmode;
typedef int strace_ioctl;
typedef int strace_fcntl;
typedef int strace_lseek;
typedef int strace_filedesc;
typedef int strace_signal;
typedef int strace_mmapprot;
typedef int strace_mmapflags;

syscnfo_t	syscalls_info[] = { 
	{ "TOTO", 0, {NULL}, "int"  },
	{ "exit", 1, {  "int", NULL }, "void"},
	{ "fork", 1, { "void", NULL }, "int"},
	{ "read", 3, {  "strace_filedesc", "void *", "size_t", NULL }, "ssize_t"},
	{ "write", 3, {  "strace_filedesc", "const void *", "size_t", NULL }, "ssize_t"},
	{ "open", 3, { "const char *", "strace_openmode", "mode_t", NULL }, "int"},
	{ "close", 1, { "int", NULL }, "int"},
	{ "wait4", 4, { "int", "int *", "int", "struct rusage *", NULL }, "int"},
	{ "ocreat", 2, { "const char *", "mode_t", NULL }, "int"},
	{ "link", 2, { "const char *", "const char *", NULL }, "int"},
	{ "unlink", 1, { "const char *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "chdir", 1, { "const char *", NULL }, "int"},
	{ "fchdir", 1, { "int", NULL }, "int"},
	{ "mknod", 3, { "const char *", "mode_t", "dev_t", NULL }, "int"},
	{ "chmod", 2, { "const char *", "mode_t", NULL }, "int"},
	{ "chown", 3, { "const char *", "uid_t", "gid_t", NULL }, "int"},
	{ "break", 1, { "char *", NULL }, "int"},
	{ "getfsstat", 3, { "struct statfs12 *", "long", "int", NULL }, "int"},
	{ "olseek", 3, { "int", "long", "int", NULL }, "long"},
	{ "getpid", 1, { "void", NULL }, "pid_t"},
	{ "mount", 4, { "const char *", "const char *", "int", "void *", NULL }, "int"},
	{ "unmount", 2, { "const char *", "int", NULL }, "int"},
	{ "setuid", 1, { "uid_t", NULL }, "int"},
	{ "getuid", 1, { "void", NULL }, "uid_t"},
	{ "geteuid", 1, { "void", NULL }, "uid_t"},
	{ "ptrace", 4, { "int", "pid_t", "caddr_t", "int", NULL }, "int"},
	{ "recvmsg", 3, { "int", "struct msghdr *", "int", NULL }, "ssize_t"},
	{ "sendmsg", 3, { "int", "const struct msghdr *", "int", NULL }, "ssize_t"},
	{ "recvfrom", 6, { "int", "void *", "size_t", "int", "struct sockaddr *", "unsigned int *", NULL }, "ssize_t"},
	{ "accept", 3, { "int", "struct sockaddr *", "unsigned int *", NULL }, "int"},
	{ "getpeername", 3, { "int", "struct sockaddr *", "unsigned int *", NULL }, "int"},
	{ "getsockname", 3, { "int", "struct sockaddr *", "unsigned int *", NULL }, "int"},
	{ "access", 2, { "const char *", "strace_accessmode", NULL }, "int"},
	{ "chflags", 2, { "const char *", "u_long", NULL }, "int"},
	{ "fchflags", 2, { "int", "u_long", NULL }, "int"},
	{ "sync", 1, { "void", NULL }, "void"},
	{ "kill", 2, { "int", "strace_signal", NULL }, "int"},
	{ "stat43", 2, { "const char *", "struct stat43 *", NULL }, "int"},
	{ "getppid", 1, { "void", NULL }, "pid_t"},
	{ "lstat43", 2, { "const char *", "struct stat43 *", NULL }, "int"},
	{ "dup", 1, { "int", NULL }, "int"},
	{ "pipe", 1, { "void", NULL }, "int"},
	{ "getegid", 1, { "void", NULL }, "gid_t"},
	{ "profil", 4, { "caddr_t", "size_t", "u_long", "u_int", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "sigaction13", 3, { "int", "const struct sigaction13 *", "struct sigaction13 *", NULL }, "int"},
	{ "getgid", 1, { "void", NULL }, "gid_t"},
	{ "sigprocmask13", 2, { "int", "int", NULL }, "int"},
	{ "getlogin", 2, { "char *", "size_t", NULL }, "int"},
	{ "setlogin", 1, { "const char *", NULL }, "int"},
	{ "acct", 1, { "const char *", NULL }, "int"},
	{ "sigpending13", 1, { "void", NULL }, "int"},
	{ "sigaltstack13", 2, { " const struct sigaltstack13 *", "struct sigaltstack13 *", NULL }, "int"},
	{ "ioctl", 3, {  "strace_filedesc", "strace_ioctl", "void *", NULL }, "int"},
	{ "oreboot", 1, { "int", NULL }, "int"},
	{ "revoke", 1, { "const char *", NULL }, "int"},
	{ "symlink", 2, { "const char *", "const char *", NULL }, "int"},
	{ "readlink", 3, { "const char *", "char *", "size_t", NULL }, "ssize_t"},
	{ "execve", 3, { "const char *", "char * const *", "char * const *", NULL }, "int"},
	{ "umask", 1, { "mode_t", NULL }, "mode_t"},
	{ "chroot", 1, { "const char *", NULL }, "int"},
	{ "fstat43", 2, { "int", "struct stat43 *", NULL }, "int"},
	{ "ogetkerninfo", 4, { "int", "char *", "int *", "int", NULL }, "int"},
	{ "ogetpagesize", 1, { "void", NULL }, "int"},
	{ "msync", 2, { "caddr_t", "size_t", NULL }, "int"},
	{ "vfork", 1, { "void", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "sbrk", 1, { "intptr_t", NULL }, "int"},
	{ "sstk", 1, { "int", NULL }, "int"},
	{ "ommap", 6, { "caddr_t", "size_t", "int", "int", "int", "long", NULL }, "int"},
	{ "vadvise", 1, { "int", NULL }, "int"},
	{ "munmap", 2, { "void *", "size_t", NULL }, "int"},
	{ "mprotect", 3, { "void *", "size_t", "int", NULL }, "int"},
	{ "madvise", 3, { "void *", "size_t", "int", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "mincore", 3, { "void *", "size_t", "char *", NULL }, "int"},
	{ "getgroups", 2, { "int", "gid_t *", NULL }, "int"},
	{ "setgroups", 2, { "int", "const gid_t *", NULL }, "int"},
	{ "getpgrp", 1, { "void", NULL }, "int"},
	{ "setpgid", 2, { "int", "int", NULL }, "int"},
	{ "setitimer", 3, { "int", "const struct itimerval *", "struct itimerval *", NULL }, "int"},
	{ "owait", 1, { "void", NULL }, "int"},
	{ "oswapon", 1, { "const char *", NULL }, "int"},
	{ "getitimer", 2, { "int", "struct itimerval *", NULL }, "int"},
	{ "ogethostname", 2, { "char *", "u_int", NULL }, "int"},
	{ "osethostname", 2, { "char *", "u_int", NULL }, "int"},
	{ "ogetdtablesize", 1, { "void", NULL }, "int"},
	{ "dup2", 2, { "int", "int", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "fcntl", 3, {  "strace_filedesc", "strace_fcntl", "void *", NULL }, "int"},
	{ "select", 5, { "int", "fd_set *", "fd_set *", "fd_set *", "struct timeval *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "fsync", 1, { "int", NULL }, "int"},
	{ "setpriority", 3, { "int", "id_t", "int", NULL }, "int"},
	{ "socket", 3, { "int", "int", "int", NULL }, "int"},
	{ "connect", 3, { "int", "const struct sockaddr *", "unsigned int", NULL }, "int"},
	{ "oaccept", 3, { "int", "caddr_t", "int *", NULL }, "int"},
	{ "getpriority", 2, { "int", "id_t", NULL }, "int"},
	{ "osend", 4, { "int", "caddr_t", "int", "int", NULL }, "int"},
	{ "orecv", 4, { "int", "caddr_t", "int", "int", NULL }, "int"},
	{ "sigreturn13", 1, { "struct sigcontext13 *", NULL }, "int"},
	{ "bind", 3, { "int", "const struct sockaddr *", "unsigned int", NULL }, "int"},
	{ "setsockopt", 5, { "int", "int", "int", "const void *", "unsigned int", NULL }, "int"},
	{ "listen", 2, { "int", "int", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "osigvec", 3, { "int", "struct sigvec *", "struct sigvec *", NULL }, "int"},
	{ "osigblock", 1, { "int", NULL }, "int"},
	{ "osigsetmask", 1, { "int", NULL }, "int"},
	{ "sigsuspend13", 1, { "int", NULL }, "int"},
	{ "osigstack", 2, { "struct sigstack *", "struct sigstack *", NULL }, "int"},
	{ "orecvmsg", 3, { "int", "struct omsghdr *", "int", NULL }, "int"},
	{ "osendmsg", 3, { "int", "caddr_t", "int", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "gettimeofday", 2, { "struct timeval *", "void *", NULL }, "int"},
	{ "getrusage", 2, { "int", "struct rusage *", NULL }, "int"},
	{ "getsockopt", 5, { "int", "int", "int", "void *", "unsigned int *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "readv", 3, { "int", "const struct iovec *", "int", NULL }, "ssize_t"},
	{ "writev", 3, { "int", "const struct iovec *", "int", NULL }, "ssize_t"},
	{ "settimeofday", 2, { "const struct timeval *", "const void *", NULL }, "int"},
	{ "fchown", 3, { "int", "uid_t", "gid_t", NULL }, "int"},
	{ "fchmod", 2, { "int", "mode_t", NULL }, "int"},
	{ "orecvfrom", 6, { "int", "caddr_t", "size_t", "int", "caddr_t", "int *", NULL }, "int"},
	{ "setreuid", 2, { "uid_t", "uid_t", NULL }, "int"},
	{ "setregid", 2, { "gid_t", "gid_t", NULL }, "int"},
	{ "rename", 2, { "const char *", "const char *", NULL }, "int"},
	{ "otruncate", 2, { "const char *", "long", NULL }, "int"},
	{ "oftruncate", 2, { "int", "long", NULL }, "int"},
	{ "flock", 2, { "int", "int", NULL }, "int"},
	{ "mkfifo", 2, { "const char *", "mode_t", NULL }, "int"},
	{ "sendto", 6, { "int", "const void *", "size_t", "int", "const struct sockaddr *", "unsigned int", NULL }, "ssize_t"},
	{ "shutdown", 2, { "int", "int", NULL }, "int"},
	{ "socketpair", 4, { "int", "int", "int", "int *", NULL }, "int"},
	{ "mkdir", 2, { "const char *", "mode_t", NULL }, "int"},
	{ "rmdir", 1, { "const char *", NULL }, "int"},
	{ "utimes", 2, { "const char *", "const struct timeval *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "adjtime", 2, { "const struct timeval *", "struct timeval *", NULL }, "int"},
	{ "ogetpeername", 3, { "int", "caddr_t", "int *", NULL }, "int"},
	{ "ogethostid", 1, { "void", NULL }, "int32_t"},
	{ "osethostid", 1, { "int32_t", NULL }, "int"},
	{ "ogetrlimit", 2, { "int", "struct orlimit *", NULL }, "int"},
	{ "osetrlimit", 2, { "int", "const struct orlimit *", NULL }, "int"},
	{ "okillpg", 2, { "int", "int", NULL }, "int"},
	{ "setsid", 1, { "void", NULL }, "int"},
	{ "quotactl", 4, { "const char *", "int", "int", "caddr_t", NULL }, "int"},
	{ "oquota", 1, { "void", NULL }, "int"},
	{ "ogetsockname", 3, { "int", "caddr_t", "int *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "ogetdirentries", 4, { "int", "char *", "u_int", "long *", NULL }, "int"},
	{ "statfs", 2, { "const char *", "struct statfs12 *", NULL }, "int"},
	{ "fstatfs", 2, { "int", "struct statfs12 *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "getfh", 2, { "const char *", "fhandle_t *", NULL }, "int"},
	{ "ogetdomainname", 2, { "char *", "int", NULL }, "int"},
	{ "osetdomainname", 2, { "char *", "int", NULL }, "int"},
	{ "ouname", 1, { "struct outsname *", NULL }, "int"},
	{ "sysarch", 2, { "int", "void *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "pread", 5, { "int", "void *", "size_t", "int", "off_t", NULL }, "ssize_t"},
	{ "pwrite", 5, { "int", "const void *", "size_t", "int", "off_t", NULL }, "ssize_t"},
	{ "ntp_gettime", 1, { "struct ntptimeval *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "setgid", 1, { "gid_t", NULL }, "int"},
	{ "setegid", 1, { "gid_t", NULL }, "int"},
	{ "seteuid", 1, { "uid_t", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "stat12", 2, { "const char *", "struct stat12 *", NULL }, "int"},
	{ "fstat12", 2, { "int", "struct stat12 *", NULL }, "int"},
	{ "lstat12", 2, { "const char *", "struct stat12 *", NULL }, "int"},
	{ "pathconf", 2, { "const char *", "int", NULL }, "long"},
	{ "fpathconf", 2, { "int", "int", NULL }, "long"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "getrlimit", 2, { "int", "struct rlimit *", NULL }, "int"},
	{ "setrlimit", 2, { "int", "const struct rlimit *", NULL }, "int"},
	{ "getdirentries", 4, { "int", "char *", "u_int", "long *", NULL }, "int"},
	{ "mmap", 7, { "void *", "size_t", "strace_mmapprot", "strace_mmapflags", "strace_filedesc", "long", "off_t", NULL }, "void *"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "lseek", 4, {  "strace_filedesc", "int", "off_t", "strace_lseek", NULL }, "off_t"},
	{ "truncate", 3, { "const char *", "int", "off_t", NULL }, "int"},
	{ "ftruncate", 3, { "int", "int", "off_t", NULL }, "int"},
	{ "sysctl", 6, { "int *", "u_int", "void *", "size_t *", "void *", "size_t", NULL }, "int"},
	{ "mlock", 2, { "const void *", "size_t", NULL }, "int"},
	{ "munlock", 2, { "const void *", "size_t", NULL }, "int"},
	{ "undelete", 1, { "const char *", NULL }, "int"},
	{ "futimes", 2, { "int", "const struct timeval *", NULL }, "int"},
	{ "getpgid", 1, { "pid_t", NULL }, "pid_t"},
	{ "reboot", 2, { "int", "char *", NULL }, "int"},
	{ "poll", 3, { "struct pollfd *", "u_int", "int", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "clock_gettime", 2, { "clockid_t", "struct timespec *", NULL }, "int"},
	{ "clock_settime", 2, { "clockid_t", "const struct timespec *", NULL }, "int"},
	{ "clock_getres", 2, { "clockid_t", "struct timespec *", NULL }, "int"},
	{ "timer_create", 3, { "clockid_t", "struct sigevent *", "timer_t *", NULL }, "int"},
	{ "timer_delete", 1, { "timer_t", NULL }, "int"},
	{ "timer_settime", 4, { "timer_t", "int", "const struct itimerspec *", "struct itimerspec *", NULL }, "int"},
	{ "timer_gettime", 2, { "timer_t", "struct itimerspec *", NULL }, "int"},
	{ "timer_getoverrun", 1, { "timer_t", NULL }, "int"},
	{ "nanosleep", 2, { "const struct timespec *", "struct timespec *", NULL }, "int"},
	{ "fdatasync", 1, { "int", NULL }, "int"},
	{ "mlockall", 1, { "int", NULL }, "int"},
	{ "munlockall", 1, { "void", NULL }, "int"},
	{ "sigtimedwait", 3, { "const sigset_t *", "siginfo_t *", "struct timespec *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "posix_rename", 2, { "const char *", "const char *", NULL }, "int"},
	{ "swapctl", 3, { "int", "void *", "int", NULL }, "int"},
	{ "getdents", 3, { "int", "char *", "size_t", NULL }, "int"},
	{ "minherit", 3, { "void *", "size_t", "int", NULL }, "int"},
	{ "lchmod", 2, { "const char *", "mode_t", NULL }, "int"},
	{ "lchown", 3, { "const char *", "uid_t", "gid_t", NULL }, "int"},
	{ "lutimes", 2, { "const char *", "const struct timeval *", NULL }, "int"},
	{ "msync13", 3, { "void *", "size_t", "int", NULL }, "int"},
	{ "stat13", 2, { "const char *", "struct stat30 *", NULL }, "int"},
	{ "fstat13", 2, { "int", "struct stat30 *", NULL }, "int"},
	{ "lstat13", 2, { "const char *", "struct stat30 *", NULL }, "int"},
	{ "sigaltstack14", 2, { " const struct sigaltstack *", "struct sigaltstack *", NULL }, "int"},
	{ "vfork14", 1, { "void", NULL }, "int"},
	{ "posix_chown", 3, { "const char *", "uid_t", "gid_t", NULL }, "int"},
	{ "posix_fchown", 3, { "int", "uid_t", "gid_t", NULL }, "int"},
	{ "posix_lchown", 3, { "const char *", "uid_t", "gid_t", NULL }, "int"},
	{ "getsid", 1, { "pid_t", NULL }, "pid_t"},
	{ "clone", 2, { "int", "void *", NULL }, "pid_t"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "preadv", 5, { "int", "const struct iovec *", "int", "int", "off_t", NULL }, "ssize_t"},
	{ "pwritev", 5, { "int", "const struct iovec *", "int", "int", "off_t", NULL }, "ssize_t"},
	{ "sigaction14", 3, { "int", "const struct sigaction *", "struct sigaction *", NULL }, "int"},
	{ "sigpending14", 1, { "sigset_t *", NULL }, "int"},
	{ "sigprocmask14", 3, { "int", "const sigset_t *", "sigset_t *", NULL }, "int"},
	{ "sigsuspend14", 1, { "const sigset_t *", NULL }, "int"},
	{ "sigreturn14", 1, { "struct sigcontext *", NULL }, "int"},
	{ "getcwd", 2, { "char *", "size_t", NULL }, "int"},
	{ "fchroot", 1, { "int", NULL }, "int"},
	{ "fhopen", 2, { "const fhandle_t *", "int", NULL }, "int"},
	{ "fhstat", 2, { "const fhandle_t *", "struct stat *", NULL }, "int"},
	{ "fhstatfs", 2, { "const fhandle_t *", "struct statfs12 *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "lchflags", 2, { "const char *", "u_long", NULL }, "int"},
	{ "issetugid", 1, { "void", NULL }, "int"},
	{ "utrace", 3, { "const char *", "void *", "size_t", NULL }, "int"},
	{ "getcontext", 1, { "struct __ucontext *", NULL }, "int"},
	{ "setcontext", 1, { "const struct __ucontext *", NULL }, "int"},
	{ "_lwp_create", 3, { "const struct __ucontext *", "u_long", "lwpid_t *", NULL }, "int"},
	{ "_lwp_exit", 1, { "void", NULL }, "int"},
	{ "_lwp_self", 1, { "void", NULL }, "lwpid_t"},
	{ "_lwp_wait", 2, { "lwpid_t", "lwpid_t *", NULL }, "int"},
	{ "_lwp_suspend", 1, { "lwpid_t", NULL }, "int"},
	{ "_lwp_continue", 1, { "lwpid_t", NULL }, "int"},
	{ "_lwp_wakeup", 1, { "lwpid_t", NULL }, "int"},
	{ "*_lwp_getprivate", 1, { "void", NULL }, "void"},
	{ "_lwp_setprivate", 1, { "void *", NULL }, "void"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "sa_register", 4, { "sa_upcall_t", "sa_upcall_t *", "int", "ssize_t", NULL }, "int"},
	{ "sa_stacks", 2, { "int", "stack_t *", NULL }, "int"},
	{ "sa_enable", 1, { "void", NULL }, "int"},
	{ "sa_setconcurrency", 1, { "int", NULL }, "int"},
	{ "sa_yield", 1, { "void", NULL }, "int"},
	{ "sa_preempt", 1, { "int", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "sigaction_sigtramp", 5, { "int", "const struct sigaction *", "struct sigaction *", "const void *", "int", NULL }, "int"},
	{ "pmc_get_info", 3, { "int", "int", "void *", NULL }, "int"},
	{ "pmc_control", 3, { "int", "int", "void *", NULL }, "int"},
	{ "rasctl", 3, { "caddr_t", "size_t", "int", NULL }, "int"},
	{ "kqueue", 1, { "void", NULL }, "int"},
	{ "kevent", 6, { "int", "const struct kevent *", "size_t", "struct kevent *", "size_t", "const struct timespec *", NULL }, "int"},
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "TOTO", 0, {NULL}, "int"  },
	{ "fsync_range", 4, { "int", "int", "off_t", "off_t", NULL }, "int"},
	{ "uuidgen", 2, { "struct uuid *", "int", NULL }, "int"},
	{ "getvfsstat", 3, { "struct statvfs *", "size_t", "int", NULL }, "int"},
	{ "statvfs1", 3, { "const char *", "struct statvfs *", "int", NULL }, "int"},
	{ "fstatvfs1", 3, { "int", "struct statvfs *", "int", NULL }, "int"},
	{ "fhstatvfs1", 3, { "const fhandle_t *", "struct statvfs *", "int", NULL }, "int"},
	{ "extattrctl", 5, { "const char *", "int", "const char *", "int", "const char *", NULL }, "int"},
	{ "extattr_set_file", 5, { "const char *", "int", "const char *", "const void *", "size_t", NULL }, "int"},
	{ "extattr_get_file", 5, { "const char *", "int", "const char *", "void *", "size_t", NULL }, "ssize_t"},
	{ "extattr_delete_file", 3, { "const char *", "int", "const char *", NULL }, "int"},
	{ "extattr_set_fd", 5, { "int", "int", "const char *", "const void *", "size_t", NULL }, "int"},
	{ "extattr_get_fd", 5, { "int", "int", "const char *", "void *", "size_t", NULL }, "ssize_t"},
	{ "extattr_delete_fd", 3, { "int", "int", "const char *", NULL }, "int"},
	{ "extattr_set_link", 5, { "const char *", "int", "const char *", "const void *", "size_t", NULL }, "int"},
	{ "extattr_get_link", 5, { "const char *", "int", "const char *", "void *", "size_t", NULL }, "ssize_t"},
	{ "extattr_delete_link", 3, { "const char *", "int", "const char *", NULL }, "int"},
	{ "extattr_list_fd", 4, { "int", "int", "void *", "size_t", NULL }, "ssize_t"},
	{ "extattr_list_file", 4, { "const char *", "int", "void *", "size_t", NULL }, "ssize_t"},
	{ "extattr_list_link", 4, { "const char *", "int", "void *", "size_t", NULL }, "ssize_t"},
	{ "pselect", 6, { "int", "fd_set *", "fd_set *", "fd_set *", "const struct timespec *", "const sigset_t *", NULL }, "int"},
	{ "pollts", 4, { "struct pollfd *", "u_int", "const struct timespec *", "const sigset_t *", NULL }, "int"},
	{ "setxattr", 5, { "const char *", "const char *", "void *", "size_t", "int", NULL }, "int"},
	{ "lsetxattr", 5, { "const char *", "const char *", "void *", "size_t", "int", NULL }, "int"},
	{ "fsetxattr", 5, { "int", "const char *", "void *", "size_t", "int", NULL }, "int"},
	{ "getxattr", 4, { "const char *", "const char *", "void *", "size_t", NULL }, "int"},
	{ "lgetxattr", 4, { "const char *", "const char *", "void *", "size_t", NULL }, "int"},
	{ "fgetxattr", 4, { "int", "const char *", "void *", "size_t", NULL }, "int"},
	{ "listxattr", 3, { "const char *", "char *", "size_t", NULL }, "int"},
	{ "llistxattr", 3, { "const char *", "char *", "size_t", NULL }, "int"},
	{ "flistxattr", 3, { "int", "char *", "size_t", NULL }, "int"},
	{ "removexattr", 2, { "const char *", "const char *", NULL }, "int"},
	{ "lremovexattr", 2, { "const char *", "const char *", NULL }, "int"},
	{ "fremovexattr", 2, { "int", "const char *", NULL }, "int"},
	{ "stat30", 2, { "const char *", "struct stat *", NULL }, "int"},
	{ "fstat30", 2, { "int", "struct stat *", NULL }, "int"},
	{ "lstat30", 2, { "const char *", "struct stat *", NULL }, "int"},
	{ "getdents30", 3, { "int", "char *", "size_t", NULL }, "int"},
	{ "posix_fadvise", 4, { "int", "off_t", "off_t", "int", NULL }, "int"},

};


#include <sys/param.h>
#include <sys/systm.h>
#include <sys/signal.h>
#include <sys/mount.h>
#include <sys/sa.h>
#include <sys/syscallargs.h>
#ifdef COMPAT_43
#else
#endif
#ifdef COMPAT_43
#else
#endif
#if defined(KTRACE) || !defined(_KERNEL)
#else
#endif
#ifdef COMPAT_43
#else
#endif
#if defined(NFS) || defined(NFSSERVER) || !defined(_KERNEL)
#else
#endif
#if (defined(SYSVSEM) || !defined(_KERNEL)) && !defined(_LP64)
#else
#endif
#if (defined(SYSVMSG) || !defined(_KERNEL)) && !defined(_LP64)
#else
#endif
#if (defined(SYSVSHM) || !defined(_KERNEL)) && !defined(_LP64)
#else
#endif
#if defined(NTP) || !defined(_KERNEL)
#else
#endif
#if defined(LFS) || !defined(_KERNEL)
#else
#endif
#if defined(LKM) || !defined(_KERNEL)
#else	/* !LKM */
#endif	/* !LKM */
#if defined(SYSVSEM) || !defined(_KERNEL)
#else
#endif
#if defined(SYSVMSG) || !defined(_KERNEL)
#else
#endif
#if defined(SYSVSHM) || !defined(_KERNEL)
#else
#endif
#if defined(P1003_1B_SEMAPHORE) || (!defined(_KERNEL) && defined(_LIBC))
#else
#endif
#if defined(KTRACE) || !defined(_KERNEL)
#else
#endif
#if defined(SYSVSEM) || !defined(_KERNEL)
#else
#endif
#if defined(SYSVMSG) || !defined(_KERNEL)
#else
#endif
#if defined(SYSVSHM) || !defined(_KERNEL)
#else
#endif

#include <ucontext.h>
#include <sys/time.h>

typedef int acl_type_t;
typedef int semid_t;
typedef unsigned int osigset_t;

typedef struct
{
  char*	str;
  int	size;
} param_size_t;

param_size_t	params_size[] =
  {
	{"struct sigaltstack13 *", sizeof(struct sigaltstack13 *)},
	{"struct __ucontext *", sizeof(struct __ucontext *)},
	{"sigset_t *", sizeof(sigset_t *)},
	{"key_t", sizeof(key_t)},
	{"struct timeval *", sizeof(struct timeval *)},
	{"caddr_t", sizeof(caddr_t)},
	{"clockid_t", sizeof(clockid_t)},
	{"struct sembuf *", sizeof(struct sembuf *)},
	{"struct sigevent *", sizeof(struct sigevent *)},
	{"unsigned int *", sizeof(unsigned int *)},
	{"struct shmid_ds *", sizeof(struct shmid_ds *)},
	{"sa_upcall_t *", sizeof(sa_upcall_t *)},
	{"strace_ioctl", sizeof(strace_ioctl)},
	{"int *", sizeof(int *)},
	{"struct msqid_ds14 *", sizeof(struct msqid_ds14 *)},
	{"struct omsghdr *", sizeof(struct omsghdr *)},
	{"int", sizeof(int)},
	{"struct sigaction13 *", sizeof(struct sigaction13 *)},
	{"fd_set *", sizeof(fd_set *)},
	{"long *", sizeof(long *)},
	{"struct msqid_ds *", sizeof(struct msqid_ds *)},
	{"uid_t", sizeof(uid_t)},
	{"sa_upcall_t", sizeof(sa_upcall_t)},
	{"uid_t", sizeof(uid_t)},
	{"const struct sigaltstack13 *", sizeof(const struct sigaltstack13 *)},
	{"ssize_t", sizeof(ssize_t)},
	{"struct statfs12 *", sizeof(struct statfs12 *)},
	{"struct statvfs *", sizeof(struct statvfs *)},
	{"strace_openmode", sizeof(strace_openmode)},
	{"const struct msghdr *", sizeof(const struct msghdr *)},
	{"size_t", sizeof(size_t)},
	{"strace_lseek", sizeof(strace_lseek)},
	{"struct kevent *", sizeof(struct kevent *)},
	{"struct timespec *", sizeof(struct timespec *)},
	{"semid_t", sizeof(semid_t)},
	{"struct sockaddr *", sizeof(struct sockaddr *)},
	{"timer_t *", sizeof(timer_t *)},
	{"const struct sockaddr *", sizeof(const struct sockaddr *)},
	{"strace_mmapflags", sizeof(strace_mmapflags)},
	{"struct block_info *", sizeof(struct block_info *)},
	{"strace_accessmode", sizeof(strace_accessmode)},
	{"char *", sizeof(char *)},
	{"strace_filedesc", sizeof(strace_filedesc)},
	{"gid_t *", sizeof(gid_t *)},
	{"pid_t", sizeof(pid_t)},
	{"intptr_t", sizeof(intptr_t)},
	{"const struct sigaction *", sizeof(const struct sigaction *)},
	{"const fhandle_t *", sizeof(const fhandle_t *)},
	{"struct sigcontext *", sizeof(struct sigcontext *)},
	{"id_t", sizeof(id_t)},
	{"const sigset_t *", sizeof(const sigset_t *)},
	{"caddr_t", sizeof(caddr_t)},
	{"const sigset_t *", sizeof(const sigset_t *)},
	{"const struct itimerspec *", sizeof(const struct itimerspec *)},
	{"int *", sizeof(int *)},
	{"struct itimerval *", sizeof(struct itimerval *)},
	{"const struct sigaltstack *", sizeof(const struct sigaltstack *)},
	{"struct statfs12 *", sizeof(struct statfs12 *)},
	{"struct stat12 *", sizeof(struct stat12 *)},
	{"long", sizeof(long)},
	{"stack_t *", sizeof(stack_t *)},
	{"off_t", sizeof(off_t)},
	{"siginfo_t *", sizeof(siginfo_t *)},
	{"const struct itimerval *", sizeof(const struct itimerval *)},
	{"unsigned int", sizeof(unsigned int)},
	{"const void *", sizeof(const void *)},
	{"struct rlimit *", sizeof(struct rlimit *)},
	{"u_int", sizeof(u_int)},
	{"strace_fcntl", sizeof(strace_fcntl)},
	{"struct sigaction *", sizeof(struct sigaction *)},
	{"const struct orlimit *", sizeof(const struct orlimit *)},
	{"struct itimerspec *", sizeof(struct itimerspec *)},
	{"struct shmid_ds14 *", sizeof(struct shmid_ds14 *)},
	{"strace_mmapprot", sizeof(strace_mmapprot)},
	{"void *", sizeof(void *)},
	{"u_long", sizeof(u_long)},
	{"const struct timeval *", sizeof(const struct timeval *)},
	{"struct statvfs *", sizeof(struct statvfs *)},
	{"const struct timespec *", sizeof(const struct timespec *)},
	{"const struct __ucontext *", sizeof(const struct __ucontext *)},
	{"const gid_t *", sizeof(const gid_t *)},
	{"int", sizeof(int)},
	{"struct ntptimeval *", sizeof(struct ntptimeval *)},
	{"void *", sizeof(void *)},
	{"const struct rlimit *", sizeof(const struct rlimit *)},
	{"void", sizeof(void)},
	{"mode_t", sizeof(mode_t)},
	{"const struct timeval *", sizeof(const struct timeval *)},
	{"struct pollfd *", sizeof(struct pollfd *)},
	{"struct timeval *", sizeof(struct timeval *)},
	{"char *", sizeof(char *)},
	{"sigset_t *", sizeof(sigset_t *)},
	{"strace_signal", sizeof(strace_signal)},
	{"struct stat30 *", sizeof(struct stat30 *)},
	{"lwpid_t *", sizeof(lwpid_t *)},
	{"union __semun *", sizeof(union __semun *)},
	{"int32_t", sizeof(int32_t)},
	{"struct outsname *", sizeof(struct outsname *)},
	{"const char *", sizeof(const char *)},
	{"lwpid_t", sizeof(lwpid_t)},
	{"struct sigvec *", sizeof(struct sigvec *)},
	{"char * const *", sizeof(char * const *)},
	{"struct stat43 *", sizeof(struct stat43 *)},
	{"struct orlimit *", sizeof(struct orlimit *)},
	{"const char *", sizeof(const char *)},
	{"pid_t", sizeof(pid_t)},
	{"struct timex *", sizeof(struct timex *)},
	{"const struct iovec *", sizeof(const struct iovec *)},
	{"gid_t", sizeof(gid_t)},
	{"fsid_t *", sizeof(fsid_t *)},
	{"const int", sizeof(const int)},
	{"struct rusage *", sizeof(struct rusage *)},
	{"dev_t", sizeof(dev_t)},
	{"fhandle_t *", sizeof(fhandle_t *)},
	{"mode_t", sizeof(mode_t)},
	{"struct sigcontext13 *", sizeof(struct sigcontext13 *)},
	{"struct sigstack *", sizeof(struct sigstack *)},
	{"timer_t", sizeof(timer_t)},
	{"const struct timespec *", sizeof(const struct timespec *)},
	{"struct uuid *", sizeof(struct uuid *)},
	{"struct msghdr *", sizeof(struct msghdr *)},
	{"const struct kevent *", sizeof(const struct kevent *)},
	{"unsigned int", sizeof(unsigned int)},
	{"struct sigaltstack *", sizeof(struct sigaltstack *)},
	{"semid_t *", sizeof(semid_t *)},
	{"const struct sigaction13 *", sizeof(const struct sigaction13 *)},
	{"size_t *", sizeof(size_t *)},
	{"gid_t", sizeof(gid_t)},
	{"struct stat *", sizeof(struct stat *)},
	{"struct sigstack *", sizeof(struct sigstack *)},
	{"const void *", sizeof(const void *)},

};
