find-tree:
	# PWD = $(PWD)
	# $(findstring /c/home/mecklen/book/admin,$(PWD))
	# $(findstring /c/home/mecklen/book/bin,$(PWD))
	# $(findstring /c/home/mecklen/book/dblite_0.5,$(PWD))
	# $(findstring /c/home/mecklen/book/examples,$(PWD))
	# $(findstring /c/home/mecklen/book/out,$(PWD))
	# $(findstring /c/home/mecklen/book/text,$(PWD))
