SHELL := /bin/ash
.PHONY: x
x:
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk; \
	$(MAKE) --no-print-directory --silent -q make-ash.mk
