SHELL = /bin/bash
.PHONY: x
x:
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk; \
	$(MAKE) --no-print-directory --silent -q make.mk
