# 100 sed using bash
SHELL := /bin/bash
.PHONY: sed-bash
sed-bash:
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
