# 100 sed using ash
SHELL := /bin/ash
.PHONY: sed-ash
sed-ash:
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
