# 100 sed using ash
SHELL := /bin/sh
.PHONY: sed-sh
sed-sh:
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
