#!/usr/bin/perl -p
#
#  htmldec.pl - Decode HTML entities as generated by htmlenc.pl
#  Copyright (C) 2007  Clifford Wolf <clifford@clifford.at>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or

s/&nbsp;/ /g;
s/&#([0-9]+);/chr($1)/ge;

