#! /bin/sh
# #############################################################################

       NAME_="emailadext"
       HTML_="isolate email address"
    PURPOSE_="extract email addresses from file or stdin"
   SYNOPSIS_="$NAME_ [-hl] <file> [file...]"
   REQUIRES_="standard GNU commands"
    VERSION_="1.0"
       DATE_="2004-06-24; last update: 2004-06-25"
     AUTHOR_="Dawid Michalczyk <dm@eonworks.com>"
        URL_="www.comp.eonworks.com"
   CATEGORY_="www"
   PLATFORM_="Linux"
      SHELL_="bash"
 DISTRIBUTE_="yes"

# #############################################################################
# This program is distributed under the terms of the GNU General Public License

usage () {

echo >&2 "$NAME_ $VERSION_ - $PURPOSE_
Usage: $SYNOPSIS_
Requires: $REQUIRES_
Options:
     -h, usage and options (this help)
     -l, see this script"
    exit 1
}

# options
case $1 in
    -h) usage ;;
    -l) more $0 ; exit 1 ;;
esac
    
# main
cat "$@" | { # so we can act as a filter
tr ',;<>()"\47 ' '[\n*]' | sed -n -e 's/mailto://gI' -e '/@/p' 
}

